### ISSUE TITLE
Home/Away

### ISSUE THREAD

**Issue by KeithL52** [mmillmor/heatmiser_netmonitor#1]
Hi

Thanks for the update, I already have the integration installed via HACS, I updated it and the link to documentation is still https://www.home-assistant.io/integrations/heatmiser_netmonitor.

For the Home/Away I was thinking about something much simpler than the "Holiday" service you have added, just a button to replicate the "Set away" / "Set home" in the Heatmiser app, is that possible ? similar to what you have now but without the dates ?

Thanks in anticipation.

Great work !!

**Comment by mmillmor** [comment]
Good idea. I have added services for home and away now too. And changed the documentation link!

**Comment by KeithL52** [comment]
Its a good job that you have made this integration as Heatmiser have discontinued the support for systems with a NetMonitor including removing the app from the Google Play Store !

I rang them today and their only advice was to replace the whole system with the Neo version !

Companies should be forced into supporting systems for a reasonable length of time which in the case of a house is longer than 10 years, I did make the point to them that this is not a throw away toy !

Thanks again for the integration.

PS someone is currently trying to sell a NetMonitor on eBay for £1000, listing says it is "very rare " !
